name: Update New Code

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Node Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy file to UAT server
        uses: appleboy/scp-action@master
        with:
          host: 54.210.175.237
          username: ubuntu
          key: AAAAB3NzaC1yc2EAAAADAQABAAACAQDyhv89c7Uw61/3cCcH0FonkkmMyJQ4frfcUqlmpkN+5OXj5HEMDp0vVDsWppKyDnzgqBmUp30CyM2FXKTbPkdAHAeF743ttHfeod/JOFpAueXigtvE9rp+U9xi0B/gH+/4TxdCmoqgG0ADtRAbi9tSezPSgKDb/zFJvMxw/AcZg+ZZesXl0j+IexJNcyRs8AdC9btJXQ6ditI/a6OMeI2u9eI+iYwue2/P4IqkbTSxs7nF71UmtzCJZkitO3K9x6VtI8Lk1p4UuJ3TRaVWAbfqnXgzB0lUe+U+hF9wFKoKYkxiXrIDxsBCpPRkX9dc6Z+4ajB8DM2YerKmEdNb4ZQkEeGIUlqWEXA3nxON6P6DRBZcW5aA14PbFHYc549BGW6Z9eN3n83N8D55kXKTfH5aYfkLDluKX25hKi6wOV7Nmz/8Qx+iROPsg6JkOelVBDbrI4N7PepQ+SXxNLJM2hPKX0lF1lbJwTqmaB7a8iC36Z2xYlaa98qy8qkMVozxqAeWcUH3xxpMW24MPVFUN5tuKp70HtPoqM4E6ZFS/6gCr2ZtFnkfeF4/mhGZ5izLd89/x6q0A24ypxdsi7JVOS16xNsf52FZLVs0yfl6tPbVzXgl19iR6gLfF1AEFznFTrh0LH2lRfldSThARwmWi4rWgnhAxH/pysDC3wGvFjVuuQ
          script: |
            sudo su
            cd /
            cd /var/www/html/call-app-backend
            git pull origin main
            npm install
            pm2 restart 0