name: Update New Code

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Node Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy file to UAT server
        uses: appleboy/scp-action@master
        with:
          host: 54.210.175.237
          username: ubuntu
          script: |
            cd /var/www/html/call-app-backend
            git pull origin main
            npm install
            pm2 restart 0